name: ci code base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/ci@v3
        with:
          node-version: '20'

      - name: Install Dependencies
         run: npm install

      - name: Run Tests
         run: npm test

      - name: Build Application
         run: npm run build

      - name: Notify on Success
          if: success()
         run: echo "Workflow completed successfully!"

      - name: Notify on Failure
          if: failure()
         run: echo "Workflow failed!"

  notify:
      needs: build
    runs-on: ubuntu-latest
      steps:
    - name: Send Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI/CD Workflow completed."}' $SLACK_WEBHOOK_URL
