name: ci Code Base

on: push

jobs:
   ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CI
        uses: github/ci@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_Token: ${{ secrets.GITHUB_TOKEN }}
